### ISSUE TITLE
执行 npm run rpc 命令时报错。出现下面的错

### ISSUE THREAD

**Issue by CNYeFeng** [dubbo/egg-dubbo-rpc#5]
PluginSequencifyError: sequencify plugins has problem, missing: [rpc], recursive: []
        >> Plugin [rpc] is disabled or missed, but is required by [dubboRpc]

**Comment by gxcsoccer** [comment]
需要安装并开启 rpc 插件，dubboRpc 依赖该插件

```bash
$ npm i egg-rpc-base --save
```

```js
// config/plugin.js
exports.rpc = true;
```
